name: Daily YAMAP Like

on:
  workflow_dispatch:
  schedule:
    # 日本時間の毎日12:00 (UTC 03:00) に実行
    - cron: '0 3 * * *'

jobs:
  trigger-jules-session:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jules API to start YAMAP Like session
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
        run: |
          JSON_PAYLOAD=$(printf '{
            "prompt": "AGENTS.mdの指示に従い、このリポジトリのSecretsに設定されているYAMAP_EMAILとYAMAP_PASSWORDを使用して `go run main.go` を実行し、YAMAPのタイムライン投稿に自動で「いいね」をしてください。",
            "sourceContext": {
              "source": "sources/github/%s",
              "githubRepoContext": {
                "startingBranch": "main"
              }
            },
            "title": "Daily YAMAP Like"
          }' "$GITHUB_REPOSITORY")

          # APIを呼び出す
          curl -f -X POST 'https://jules.googleapis.com/v1alpha/sessions' \
          -H 'Content-Type: application/json' \
          -H "X-Goog-Api-Key: $JULES_API_KEY" \
          -d "$JSON_PAYLOAD"